version: "3"

services:
  discovery-service:
    image: openjdk:8
    hostname: discovery-service
    container_name: discovery-service
    environment:
      - TZ=Asia/Seoul 
    ports:
      - 8761:8761
    volumes:
      - ./src/main/resources:/app/resources
      - ./target:/app/target
    command: java -jar \
             -Dspring.config.location=/app/resources/application.yml \
             /app/target/spring-discovery-service-0.0.1-SNAPSHOT.jar
    networks:
      - eureka_net

networks:
  eureka_net:
    name: eureka_net
    external: true
